/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ibex_branch_predict_gate(clk_i, rst_ni, fetch_rdata_i, fetch_pc_i, fetch_valid_i, predict_branch_taken_o, predict_branch_pc_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] fetch_rdata_i;
  wire [31:0] fetch_rdata_i;
  input [31:0] fetch_pc_i;
  wire [31:0] fetch_pc_i;
  input fetch_valid_i;
  wire fetch_valid_i;
  output predict_branch_taken_o;
  wire predict_branch_taken_o;
  output [31:0] predict_branch_pc_o;
  wire [31:0] predict_branch_pc_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire [31:0] branch_imm;
  wire [31:0] instr;
  sky130_fd_sc_hd__nand3_1 _177_ (
    .A(_147_),
    .B(_148_),
    .C(_150_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_151_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xor2_1 _179_ (
    .A(fetch_pc_i[26]),
    .B(_092_),
    .X(_154_)
  );
  sky130_fd_sc_hd__xor2_1 _180_ (
    .A(_153_),
    .B(_154_),
    .X(predict_branch_pc_o[26])
  );
  sky130_fd_sc_hd__maj3_1 _181_ (
    .A(fetch_pc_i[26]),
    .B(_092_),
    .C(_153_),
    .X(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _182_ (
    .A(fetch_pc_i[27]),
    .B(_092_),
    .X(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _183_ (
    .A(_155_),
    .B(_156_),
    .X(predict_branch_pc_o[27])
  );
  sky130_fd_sc_hd__and2_0 _184_ (
    .A(_154_),
    .B(_156_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand4_1 _185_ (
    .A(_147_),
    .B(_148_),
    .C(_150_),
    .D(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o41ai_1 _186_ (
    .A1(fetch_pc_i[24]),
    .A2(fetch_pc_i[26]),
    .A3(fetch_pc_i[25]),
    .A4(fetch_pc_i[27]),
    .B1(_092_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(fetch_pc_i[28]),
    .B(_092_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(_158_),
    .A2(_159_),
    .B1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand3_1 _189_ (
    .A(_158_),
    .B(_159_),
    .C(_160_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2b_1 _190_ (
    .A(_161_),
    .B_N(_162_),
    .Y(predict_branch_pc_o[28])
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(fetch_pc_i[28]),
    .A2(_092_),
    .B1(_161_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(fetch_pc_i[29]),
    .B(_092_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _193_ (
    .A(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(fetch_pc_i[29]),
    .B(_092_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _195_ (
    .A(_165_),
    .SLEEP(_166_),
    .X(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _196_ (
    .A(_163_),
    .B(_167_),
    .X(predict_branch_pc_o[29])
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(fetch_pc_i[30]),
    .B(_092_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(fetch_pc_i[30]),
    .B(_092_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a211oi_1 _199_ (
    .A1(fetch_pc_i[28]),
    .A2(_092_),
    .B1(_161_),
    .C1(_165_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_166_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(_169_),
    .B(_171_),
    .Y(predict_branch_pc_o[30])
  );
  sky130_fd_sc_hd__o31ai_1 _202_ (
    .A1(_166_),
    .A2(_169_),
    .A3(_170_),
    .B1(_168_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(fetch_pc_i[31]),
    .B(_092_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__xnor2_1 _204_ (
    .A(_172_),
    .B(_173_),
    .Y(predict_branch_pc_o[31])
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(_174_),
    .B(_018_),
    .Y(predict_branch_pc_o[1])
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(fetch_pc_i[1]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__clkinv_1 _207_ (
    .A(fetch_pc_i[9]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(fetch_pc_i[15]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(fetch_rdata_i[1]),
    .B(fetch_rdata_i[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand3b_1 _210_ (
    .A_N(fetch_rdata_i[4]),
    .B(fetch_rdata_i[5]),
    .C(fetch_rdata_i[6]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(fetch_rdata_i[2]),
    .B(fetch_rdata_i[3]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _212_ (
    .A(_000_),
    .B(_001_),
    .C(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__or3_1 _213_ (
    .A(_000_),
    .B(_001_),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__and4b_1 _214_ (
    .A_N(fetch_rdata_i[1]),
    .B(fetch_rdata_i[0]),
    .C(fetch_rdata_i[15]),
    .D(fetch_rdata_i[14]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand4b_1 _215_ (
    .A_N(fetch_rdata_i[1]),
    .B(fetch_rdata_i[0]),
    .C(fetch_rdata_i[15]),
    .D(fetch_rdata_i[14]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(fetch_rdata_i[12]),
    .B(_005_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor4bb_1 _217_ (
    .A(fetch_rdata_i[1]),
    .B(fetch_rdata_i[14]),
    .C_N(fetch_rdata_i[13]),
    .D_N(fetch_rdata_i[0]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand4bb_1 _218_ (
    .A_N(fetch_rdata_i[1]),
    .B_N(fetch_rdata_i[14]),
    .C(fetch_rdata_i[13]),
    .D(fetch_rdata_i[0]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand3_1 _219_ (
    .A(_004_),
    .B(_007_),
    .C(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor4_1 _220_ (
    .A(fetch_rdata_i[2]),
    .B(fetch_rdata_i[3]),
    .C(_000_),
    .D(_001_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21oi_1 _221_ (
    .A1(fetch_rdata_i[31]),
    .A2(_011_),
    .B1(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _222_ (
    .A(fetch_valid_i),
    .SLEEP(_012_),
    .X(predict_branch_taken_o)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(_005_),
    .B(_008_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_006_),
    .B(_009_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand3_1 _225_ (
    .A(fetch_rdata_i[8]),
    .B(_006_),
    .C(_009_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_005_),
    .A2(_008_),
    .B1(fetch_rdata_i[3]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor4_1 _227_ (
    .A(fetch_rdata_i[21]),
    .B(_000_),
    .C(_001_),
    .D(_002_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a31oi_1 _228_ (
    .A1(_004_),
    .A2(_015_),
    .A3(_016_),
    .B1(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a311oi_1 _229_ (
    .A1(_004_),
    .A2(_015_),
    .A3(_016_),
    .B1(_017_),
    .C1(_174_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand3_1 _230_ (
    .A(fetch_rdata_i[9]),
    .B(_006_),
    .C(_009_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_005_),
    .A2(_008_),
    .B1(fetch_rdata_i[4]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor4_1 _232_ (
    .A(fetch_rdata_i[22]),
    .B(_000_),
    .C(_001_),
    .D(_002_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _233_ (
    .A1(_004_),
    .A2(_020_),
    .A3(_021_),
    .B1(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _234_ (
    .A(fetch_pc_i[2]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _235_ (
    .A(_019_),
    .B(_024_),
    .Y(predict_branch_pc_o[2])
  );
  sky130_fd_sc_hd__maj3_1 _236_ (
    .A(fetch_pc_i[2]),
    .B(_019_),
    .C(_023_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2i_1 _237_ (
    .A0(fetch_rdata_i[10]),
    .A1(fetch_rdata_i[5]),
    .S(_008_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _238_ (
    .A(_003_),
    .B(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_004_),
    .B(_026_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o211a_1 _240_ (
    .A1(fetch_rdata_i[23]),
    .A2(_004_),
    .B1(_028_),
    .C1(fetch_pc_i[3]),
    .X(_029_)
  );
  sky130_fd_sc_hd__a211o_1 _241_ (
    .A1(fetch_rdata_i[23]),
    .A2(_003_),
    .B1(_027_),
    .C1(fetch_pc_i[3]),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2b_1 _242_ (
    .A_N(_029_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(_025_),
    .B(_031_),
    .Y(predict_branch_pc_o[3])
  );
  sky130_fd_sc_hd__mux2i_1 _244_ (
    .A0(fetch_rdata_i[11]),
    .A1(fetch_rdata_i[24]),
    .S(_003_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _245_ (
    .A_N(_032_),
    .B(fetch_pc_i[4]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(fetch_pc_i[4]),
    .B(_032_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _248_ (
    .A1(_025_),
    .A2(_029_),
    .B1(_030_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o211a_1 _249_ (
    .A1(_025_),
    .A2(_029_),
    .B1(_030_),
    .C1(_035_),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _250_ (
    .A(_035_),
    .B(_036_),
    .Y(predict_branch_pc_o[4])
  );
  sky130_fd_sc_hd__mux2i_1 _251_ (
    .A0(fetch_rdata_i[25]),
    .A1(fetch_rdata_i[2]),
    .S(_014_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _252_ (
    .A(fetch_pc_i[5]),
    .SLEEP(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(fetch_pc_i[5]),
    .B(_038_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _255_ (
    .A1(_034_),
    .A2(_037_),
    .B1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3_1 _256_ (
    .A(_034_),
    .B(_037_),
    .C(_041_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _257_ (
    .A(_042_),
    .SLEEP(_043_),
    .X(predict_branch_pc_o[5])
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(fetch_rdata_i[5]),
    .B(_005_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(fetch_rdata_i[26]),
    .B(_006_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _260_ (
    .A(_009_),
    .B(_044_),
    .C(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _261_ (
    .A1(fetch_rdata_i[7]),
    .A2(_009_),
    .B1(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _262_ (
    .A(fetch_pc_i[6]),
    .SLEEP(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__xor2_1 _263_ (
    .A(fetch_pc_i[6]),
    .B(_047_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand3_1 _265_ (
    .A(_040_),
    .B(_042_),
    .C(_049_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2b_1 _266_ (
    .A(_050_),
    .B_N(_051_),
    .Y(predict_branch_pc_o[6])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _267_ (
    .A(_048_),
    .SLEEP(_050_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2i_1 _268_ (
    .A0(fetch_rdata_i[27]),
    .A1(fetch_rdata_i[6]),
    .S(_014_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _269_ (
    .A(fetch_pc_i[7]),
    .SLEEP(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2b_1 _270_ (
    .A_N(fetch_pc_i[7]),
    .B(_053_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2b_1 _271_ (
    .A_N(_054_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _272_ (
    .A(_052_),
    .B(_056_),
    .Y(predict_branch_pc_o[7])
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(fetch_rdata_i[28]),
    .B(_013_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(fetch_rdata_i[9]),
    .B(_008_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _275_ (
    .A(_007_),
    .B(_057_),
    .C(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__and2_0 _276_ (
    .A(fetch_pc_i[8]),
    .B(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(fetch_pc_i[8]),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _279_ (
    .A1(_052_),
    .A2(_054_),
    .B1(_055_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o311a_1 _280_ (
    .A1(_048_),
    .A2(_050_),
    .A3(_054_),
    .B1(_055_),
    .C1(_062_),
    .X(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _281_ (
    .A(_062_),
    .B(_063_),
    .Y(predict_branch_pc_o[8])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _282_ (
    .A(_060_),
    .SLEEP(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(fetch_rdata_i[29]),
    .B(_013_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(fetch_rdata_i[10]),
    .B(_008_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a31oi_1 _285_ (
    .A1(_007_),
    .A2(_066_),
    .A3(_067_),
    .B1(_175_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand4_1 _286_ (
    .A(_175_),
    .B(_007_),
    .C(_066_),
    .D(_067_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2b_1 _287_ (
    .A_N(_068_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _288_ (
    .A(_065_),
    .B(_070_),
    .Y(predict_branch_pc_o[9])
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(fetch_rdata_i[30]),
    .B(_013_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(fetch_rdata_i[8]),
    .B(_008_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3_1 _291_ (
    .A(_007_),
    .B(_071_),
    .C(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(fetch_pc_i[10]),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xor2_1 _293_ (
    .A(fetch_pc_i[10]),
    .B(_073_),
    .X(_075_)
  );
  sky130_fd_sc_hd__o21ai_0 _294_ (
    .A1(_065_),
    .A2(_068_),
    .B1(_069_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o311ai_0 _295_ (
    .A1(_060_),
    .A2(_064_),
    .A3(_068_),
    .B1(_069_),
    .C1(_075_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _296_ (
    .A(_075_),
    .B(_076_),
    .Y(predict_branch_pc_o[10])
  );
  sky130_fd_sc_hd__and2_0 _297_ (
    .A(_074_),
    .B(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and2_0 _298_ (
    .A(fetch_rdata_i[12]),
    .B(_014_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(fetch_rdata_i[7]),
    .B(_003_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _300_ (
    .A1(fetch_rdata_i[20]),
    .A2(_004_),
    .B1(_013_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(_079_),
    .A2(_082_),
    .B1(fetch_pc_i[11]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor3_1 _303_ (
    .A(fetch_pc_i[11]),
    .B(_079_),
    .C(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _304_ (
    .A(_083_),
    .SLEEP(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(_078_),
    .B(_085_),
    .Y(predict_branch_pc_o[11])
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(_004_),
    .B(_013_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__mux2i_1 _307_ (
    .A0(fetch_rdata_i[31]),
    .A1(fetch_rdata_i[12]),
    .S(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _308_ (
    .A(fetch_pc_i[12]),
    .SLEEP(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(fetch_pc_i[12]),
    .B(_087_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(_078_),
    .A2(_083_),
    .B1(_084_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a311oi_1 _311_ (
    .A1(_074_),
    .A2(_077_),
    .A3(_083_),
    .B1(_084_),
    .C1(_089_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _312_ (
    .A(_089_),
    .B(_090_),
    .Y(predict_branch_pc_o[12])
  );
  sky130_fd_sc_hd__a21o_1 _313_ (
    .A1(fetch_rdata_i[31]),
    .A2(_013_),
    .B1(_079_),
    .X(_092_)
  );
  sky130_fd_sc_hd__and2_0 _314_ (
    .A(_004_),
    .B(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__a21oi_1 _315_ (
    .A1(fetch_rdata_i[13]),
    .A2(_003_),
    .B1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2b_1 _316_ (
    .A_N(_094_),
    .B(fetch_pc_i[13]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(fetch_pc_i[13]),
    .B(_094_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor3_1 _318_ (
    .A(_088_),
    .B(_091_),
    .C(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _319_ (
    .A1(_088_),
    .A2(_091_),
    .B1(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2b_1 _320_ (
    .A(_097_),
    .B_N(_098_),
    .Y(predict_branch_pc_o[13])
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(_095_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_1 _322_ (
    .A1(fetch_rdata_i[14]),
    .A2(_003_),
    .B1(_093_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2b_1 _323_ (
    .A_N(_100_),
    .B(fetch_pc_i[14]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(fetch_pc_i[14]),
    .B(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _325_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_099_),
    .B(_102_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _327_ (
    .A(_099_),
    .B(_103_),
    .Y(predict_branch_pc_o[14])
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(_101_),
    .B(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _329_ (
    .A1(fetch_rdata_i[15]),
    .A2(_003_),
    .B1(_093_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xnor2_1 _330_ (
    .A(_176_),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _331_ (
    .A(_105_),
    .B(_107_),
    .Y(predict_branch_pc_o[15])
  );
  sky130_fd_sc_hd__a211oi_1 _332_ (
    .A1(_095_),
    .A2(_098_),
    .B1(_103_),
    .C1(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21o_1 _333_ (
    .A1(_176_),
    .A2(_106_),
    .B1(_101_),
    .X(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _334_ (
    .A1(_176_),
    .A2(_106_),
    .B1(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21oi_1 _335_ (
    .A1(fetch_rdata_i[16]),
    .A2(_003_),
    .B1(_093_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2b_1 _336_ (
    .A_N(_111_),
    .B(fetch_pc_i[16]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _337_ (
    .A(fetch_pc_i[16]),
    .B(_111_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21ai_0 _338_ (
    .A1(_108_),
    .A2(_110_),
    .B1(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor3_1 _339_ (
    .A(_108_),
    .B(_110_),
    .C(_113_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _340_ (
    .A(_114_),
    .SLEEP(_115_),
    .X(predict_branch_pc_o[16])
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(_112_),
    .B(_114_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _342_ (
    .A1(fetch_rdata_i[17]),
    .A2(_003_),
    .B1(_093_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2b_1 _343_ (
    .A_N(_117_),
    .B(fetch_pc_i[17]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _344_ (
    .A(_117_),
    .SLEEP(fetch_pc_i[17]),
    .X(_119_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _345_ (
    .A(_118_),
    .SLEEP(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _346_ (
    .A(_116_),
    .B(_120_),
    .Y(predict_branch_pc_o[17])
  );
  sky130_fd_sc_hd__a21oi_1 _347_ (
    .A1(fetch_rdata_i[18]),
    .A2(_003_),
    .B1(_093_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2b_1 _348_ (
    .A_N(_121_),
    .B(fetch_pc_i[18]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _350_ (
    .A(fetch_pc_i[18]),
    .B(_121_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a31oi_1 _352_ (
    .A1(_112_),
    .A2(_114_),
    .A3(_118_),
    .B1(_119_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a311oi_1 _353_ (
    .A1(_112_),
    .A2(_114_),
    .A3(_118_),
    .B1(_119_),
    .C1(_125_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_124_),
    .B(_126_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(_127_),
    .B(_128_),
    .Y(predict_branch_pc_o[18])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _356_ (
    .A(_123_),
    .SLEEP(_127_),
    .X(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _357_ (
    .A1(fetch_rdata_i[19]),
    .A2(_003_),
    .B1(_093_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _358_ (
    .A(fetch_pc_i[19]),
    .SLEEP(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__nand2b_1 _359_ (
    .A_N(fetch_pc_i[19]),
    .B(_130_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2b_1 _360_ (
    .A_N(_131_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _361_ (
    .A(_129_),
    .B(_133_),
    .Y(predict_branch_pc_o[19])
  );
  sky130_fd_sc_hd__xor2_1 _362_ (
    .A(fetch_pc_i[20]),
    .B(_092_),
    .X(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _363_ (
    .A1(_129_),
    .A2(_132_),
    .B1(_131_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o311a_1 _364_ (
    .A1(_123_),
    .A2(_127_),
    .A3(_131_),
    .B1(_132_),
    .C1(_134_),
    .X(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(_134_),
    .B(_135_),
    .Y(predict_branch_pc_o[20])
  );
  sky130_fd_sc_hd__a21oi_1 _366_ (
    .A1(fetch_pc_i[20]),
    .A2(_092_),
    .B1(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xor2_1 _367_ (
    .A(fetch_pc_i[21]),
    .B(_092_),
    .X(_138_)
  );
  sky130_fd_sc_hd__xnor2_1 _368_ (
    .A(_137_),
    .B(_138_),
    .Y(predict_branch_pc_o[21])
  );
  sky130_fd_sc_hd__o21ai_0 _369_ (
    .A1(fetch_pc_i[21]),
    .A2(fetch_pc_i[20]),
    .B1(_092_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _370_ (
    .A(_136_),
    .B(_138_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _371_ (
    .A(_139_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xor2_1 _372_ (
    .A(fetch_pc_i[22]),
    .B(_092_),
    .X(_142_)
  );
  sky130_fd_sc_hd__xor2_1 _373_ (
    .A(_141_),
    .B(_142_),
    .X(predict_branch_pc_o[22])
  );
  sky130_fd_sc_hd__maj3_1 _374_ (
    .A(fetch_pc_i[22]),
    .B(_092_),
    .C(_141_),
    .X(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _375_ (
    .A(fetch_pc_i[23]),
    .B(_092_),
    .X(_144_)
  );
  sky130_fd_sc_hd__xor2_1 _376_ (
    .A(_143_),
    .B(_144_),
    .X(predict_branch_pc_o[23])
  );
  sky130_fd_sc_hd__and2_0 _377_ (
    .A(_142_),
    .B(_144_),
    .X(_145_)
  );
  sky130_fd_sc_hd__o41a_1 _378_ (
    .A1(fetch_pc_i[23]),
    .A2(fetch_pc_i[21]),
    .A3(fetch_pc_i[22]),
    .A4(fetch_pc_i[20]),
    .B1(_092_),
    .X(_146_)
  );
  sky130_fd_sc_hd__a31o_1 _379_ (
    .A1(_136_),
    .A2(_138_),
    .A3(_145_),
    .B1(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__xor2_1 _380_ (
    .A(fetch_pc_i[24]),
    .B(_092_),
    .X(_148_)
  );
  sky130_fd_sc_hd__xor2_1 _381_ (
    .A(_147_),
    .B(_148_),
    .X(predict_branch_pc_o[24])
  );
  sky130_fd_sc_hd__maj3_1 _382_ (
    .A(fetch_pc_i[24]),
    .B(_092_),
    .C(_147_),
    .X(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _383_ (
    .A(fetch_pc_i[25]),
    .B(_092_),
    .X(_150_)
  );
  sky130_fd_sc_hd__xor2_1 _384_ (
    .A(_149_),
    .B(_150_),
    .X(predict_branch_pc_o[25])
  );
  sky130_fd_sc_hd__o21ai_0 _385_ (
    .A1(fetch_pc_i[24]),
    .A2(fetch_pc_i[25]),
    .B1(_092_),
    .Y(_151_)
  );
  assign instr = fetch_rdata_i;
  assign { branch_imm[31:21], branch_imm[0] } = { branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], 1'b0 };
  assign predict_branch_pc_o[0] = fetch_pc_i[0];
endmodule
