/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ibex_branch_predict(clk_i, rst_ni, fetch_rdata_i, fetch_pc_i, fetch_valid_i, predict_branch_taken_o, predict_branch_pc_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] fetch_rdata_i;
  wire [31:0] fetch_rdata_i;
  input [31:0] fetch_pc_i;
  wire [31:0] fetch_pc_i;
  input fetch_valid_i;
  wire fetch_valid_i;
  output predict_branch_taken_o;
  wire predict_branch_taken_o;
  output [31:0] predict_branch_pc_o;
  wire [31:0] predict_branch_pc_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire [31:0] \_29_$func$gold_elab.v:74$2.a ;
  wire [95:0] \_29_$func$gold_elab.v:74$2.b ;
  wire [2:0] \_29_$func$gold_elab.v:74$2.s ;
  wire _sv2v_0;
  wire [31:0] branch_imm;
  wire [31:0] imm_b_type;
  wire [31:0] imm_cb_type;
  wire [31:0] imm_cj_type;
  wire [31:0] imm_j_type;
  wire [31:0] instr;
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(fetch_valid_i),
    .Y(_161_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(fetch_pc_i[17]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3b_1 _166_ (
    .A_N(fetch_rdata_i[4]),
    .B(fetch_rdata_i[5]),
    .C(fetch_rdata_i[6]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(fetch_rdata_i[1]),
    .B(fetch_rdata_i[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(fetch_rdata_i[2]),
    .B(fetch_rdata_i[3]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor3_1 _169_ (
    .A(_163_),
    .B(_000_),
    .C(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor4bb_1 _170_ (
    .A(fetch_rdata_i[1]),
    .B(fetch_rdata_i[14]),
    .C_N(fetch_rdata_i[0]),
    .D_N(fetch_rdata_i[13]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and4b_1 _172_ (
    .A_N(fetch_rdata_i[1]),
    .B(fetch_rdata_i[14]),
    .C(fetch_rdata_i[15]),
    .D(fetch_rdata_i[0]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(fetch_rdata_i[12]),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor4_1 _174_ (
    .A(fetch_rdata_i[2]),
    .B(fetch_rdata_i[3]),
    .C(_163_),
    .D(_000_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(fetch_rdata_i[31]),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a31oi_1 _176_ (
    .A1(_004_),
    .A2(_006_),
    .A3(_008_),
    .B1(_161_),
    .Y(predict_branch_taken_o)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(_003_),
    .B(_005_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _178_ (
    .A(_003_),
    .SLEEP(_005_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(_002_),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor3b_1 _180_ (
    .A(_002_),
    .B(_010_),
    .C_N(fetch_rdata_i[8]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a22o_1 _181_ (
    .A1(fetch_rdata_i[21]),
    .A2(_002_),
    .B1(_010_),
    .B2(fetch_rdata_i[3]),
    .X(_013_)
  );
  sky130_fd_sc_hd__o21a_1 _182_ (
    .A1(_012_),
    .A2(_013_),
    .B1(fetch_pc_i[1]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _183_ (
    .A(fetch_pc_i[1]),
    .B(_012_),
    .C(_013_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_014_),
    .B(_015_),
    .Y(predict_branch_pc_o[1])
  );
  sky130_fd_sc_hd__a22o_1 _185_ (
    .A1(fetch_rdata_i[22]),
    .A2(_002_),
    .B1(_010_),
    .B2(fetch_rdata_i[4]),
    .X(_016_)
  );
  sky130_fd_sc_hd__a21o_1 _186_ (
    .A1(fetch_rdata_i[9]),
    .A2(_011_),
    .B1(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(fetch_pc_i[2]),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(_014_),
    .B(_018_),
    .Y(predict_branch_pc_o[2])
  );
  sky130_fd_sc_hd__maj3_1 _189_ (
    .A(fetch_pc_i[2]),
    .B(_014_),
    .C(_017_),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(fetch_rdata_i[23]),
    .B(_002_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a22oi_1 _191_ (
    .A1(fetch_rdata_i[5]),
    .A2(_003_),
    .B1(_004_),
    .B2(fetch_rdata_i[10]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _193_ (
    .A(fetch_pc_i[3]),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _194_ (
    .A(_019_),
    .B(_023_),
    .Y(predict_branch_pc_o[3])
  );
  sky130_fd_sc_hd__maj3_1 _195_ (
    .A(fetch_pc_i[3]),
    .B(_019_),
    .C(_022_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2i_1 _196_ (
    .A0(fetch_rdata_i[11]),
    .A1(fetch_rdata_i[24]),
    .S(_002_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _197_ (
    .A(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _198_ (
    .A(fetch_pc_i[4]),
    .B(_025_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _199_ (
    .A(_024_),
    .B(_027_),
    .Y(predict_branch_pc_o[4])
  );
  sky130_fd_sc_hd__maj3_1 _200_ (
    .A(fetch_pc_i[4]),
    .B(_024_),
    .C(_026_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2i_1 _201_ (
    .A0(fetch_rdata_i[2]),
    .A1(fetch_rdata_i[25]),
    .S(_009_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _203_ (
    .A(fetch_pc_i[5]),
    .B(_029_),
    .X(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _204_ (
    .A(_028_),
    .B(_031_),
    .Y(predict_branch_pc_o[5])
  );
  sky130_fd_sc_hd__maj3_1 _205_ (
    .A(fetch_pc_i[5]),
    .B(_028_),
    .C(_030_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(fetch_rdata_i[26]),
    .B(_009_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a22oi_1 _207_ (
    .A1(fetch_rdata_i[7]),
    .A2(_003_),
    .B1(_005_),
    .B2(fetch_rdata_i[5]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _209_ (
    .A(fetch_pc_i[6]),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _210_ (
    .A(_032_),
    .B(_036_),
    .Y(predict_branch_pc_o[6])
  );
  sky130_fd_sc_hd__maj3_1 _211_ (
    .A(fetch_pc_i[6]),
    .B(_032_),
    .C(_035_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2i_1 _212_ (
    .A0(fetch_rdata_i[6]),
    .A1(fetch_rdata_i[27]),
    .S(_009_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _214_ (
    .A(fetch_pc_i[7]),
    .B(_038_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _215_ (
    .A(_037_),
    .B(_040_),
    .Y(predict_branch_pc_o[7])
  );
  sky130_fd_sc_hd__maj3_1 _216_ (
    .A(fetch_pc_i[7]),
    .B(_037_),
    .C(_039_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(fetch_rdata_i[28]),
    .B(_009_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(fetch_rdata_i[9]),
    .B(_003_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand3_1 _219_ (
    .A(_006_),
    .B(_042_),
    .C(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__and2_0 _220_ (
    .A(fetch_pc_i[8]),
    .B(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(fetch_pc_i[8]),
    .B(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _223_ (
    .A(_041_),
    .B(_047_),
    .X(predict_branch_pc_o[8])
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(_041_),
    .A2(_047_),
    .B1(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(fetch_rdata_i[29]),
    .B(_009_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(fetch_rdata_i[10]),
    .B(_003_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand3_1 _227_ (
    .A(_006_),
    .B(_049_),
    .C(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _228_ (
    .A(fetch_pc_i[9]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _229_ (
    .A(fetch_pc_i[9]),
    .B(_051_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(_048_),
    .B(_053_),
    .Y(predict_branch_pc_o[9])
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(fetch_rdata_i[30]),
    .B(_009_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(fetch_rdata_i[8]),
    .B(_003_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand3_1 _233_ (
    .A(_006_),
    .B(_054_),
    .C(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(fetch_pc_i[10]),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _235_ (
    .A(fetch_pc_i[10]),
    .B(_056_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a221oi_1 _236_ (
    .A1(_041_),
    .A2(_047_),
    .B1(_051_),
    .B2(fetch_pc_i[9]),
    .C1(_045_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_052_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _238_ (
    .A(_058_),
    .B(_060_),
    .Y(predict_branch_pc_o[10])
  );
  sky130_fd_sc_hd__o31ai_1 _239_ (
    .A1(_052_),
    .A2(_058_),
    .A3(_059_),
    .B1(_057_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and2_0 _240_ (
    .A(fetch_rdata_i[7]),
    .B(_011_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(fetch_rdata_i[20]),
    .B(_002_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(fetch_rdata_i[12]),
    .B(_010_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21a_1 _244_ (
    .A1(_062_),
    .A2(_065_),
    .B1(fetch_pc_i[11]),
    .X(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _245_ (
    .A(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__or3_1 _246_ (
    .A(fetch_pc_i[11]),
    .B(_062_),
    .C(_065_),
    .X(_068_)
  );
  sky130_fd_sc_hd__nor2b_1 _247_ (
    .A(_066_),
    .B_N(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _248_ (
    .A(_061_),
    .B(_069_),
    .X(predict_branch_pc_o[11])
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(fetch_rdata_i[31]),
    .B(_011_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__mux2i_1 _250_ (
    .A0(fetch_rdata_i[12]),
    .A1(fetch_rdata_i[31]),
    .S(_011_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _251_ (
    .A(fetch_pc_i[12]),
    .SLEEP(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _252_ (
    .A(fetch_pc_i[12]),
    .B(_071_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o311ai_0 _253_ (
    .A1(_052_),
    .A2(_058_),
    .A3(_059_),
    .B1(_067_),
    .C1(_057_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_068_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _255_ (
    .A(_073_),
    .B(_075_),
    .Y(predict_branch_pc_o[12])
  );
  sky130_fd_sc_hd__a31oi_1 _256_ (
    .A1(_068_),
    .A2(_073_),
    .A3(_074_),
    .B1(_072_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_064_),
    .B(_070_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(fetch_rdata_i[13]),
    .A2(_002_),
    .B1(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _259_ (
    .A(fetch_pc_i[13]),
    .SLEEP(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _260_ (
    .A(_078_),
    .SLEEP(fetch_pc_i[13]),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_076_),
    .B(_081_),
    .Y(predict_branch_pc_o[13])
  );
  sky130_fd_sc_hd__a21oi_1 _263_ (
    .A1(fetch_rdata_i[14]),
    .A2(_002_),
    .B1(_077_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2b_1 _264_ (
    .A_N(_082_),
    .B(fetch_pc_i[14]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(fetch_pc_i[14]),
    .B(_082_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__clkinv_1 _266_ (
    .A(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a311oi_1 _267_ (
    .A1(_068_),
    .A2(_073_),
    .A3(_074_),
    .B1(_079_),
    .C1(_072_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _268_ (
    .A(_080_),
    .SLEEP(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_084_),
    .B(_087_),
    .Y(predict_branch_pc_o[14])
  );
  sky130_fd_sc_hd__o21ai_0 _270_ (
    .A1(_085_),
    .A2(_087_),
    .B1(_083_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _271_ (
    .A1(fetch_rdata_i[15]),
    .A2(_002_),
    .B1(_077_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(fetch_pc_i[15]),
    .SLEEP(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2b_1 _274_ (
    .A_N(fetch_pc_i[15]),
    .B(_089_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(_088_),
    .B(_093_),
    .Y(predict_branch_pc_o[15])
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(fetch_rdata_i[16]),
    .A2(_002_),
    .B1(_077_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _278_ (
    .A(fetch_pc_i[16]),
    .SLEEP(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _279_ (
    .A(fetch_pc_i[16]),
    .B(_094_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o311ai_0 _280_ (
    .A1(_080_),
    .A2(_085_),
    .A3(_086_),
    .B1(_091_),
    .C1(_083_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_092_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _282_ (
    .A(_096_),
    .B(_098_),
    .Y(predict_branch_pc_o[16])
  );
  sky130_fd_sc_hd__a31oi_1 _283_ (
    .A1(_092_),
    .A2(_096_),
    .A3(_097_),
    .B1(_095_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(fetch_rdata_i[17]),
    .A2(_002_),
    .B1(_077_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xnor2_1 _285_ (
    .A(fetch_pc_i[17]),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _286_ (
    .A(_099_),
    .B(_101_),
    .Y(predict_branch_pc_o[17])
  );
  sky130_fd_sc_hd__maj3_1 _287_ (
    .A(_162_),
    .B(_099_),
    .C(_100_),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(fetch_rdata_i[18]),
    .A2(_002_),
    .B1(_077_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _289_ (
    .A(fetch_pc_i[18]),
    .SLEEP(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _290_ (
    .A(fetch_pc_i[18]),
    .B(_103_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _291_ (
    .A(_105_),
    .SLEEP(_102_),
    .X(_106_)
  );
  sky130_fd_sc_hd__xnor2_1 _292_ (
    .A(_102_),
    .B(_105_),
    .Y(predict_branch_pc_o[18])
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_104_),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(fetch_rdata_i[19]),
    .A2(_002_),
    .B1(_077_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__clkinv_1 _295_ (
    .A(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__xnor2_1 _296_ (
    .A(fetch_pc_i[19]),
    .B(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _297_ (
    .A(_107_),
    .B(_110_),
    .Y(predict_branch_pc_o[19])
  );
  sky130_fd_sc_hd__and3b_1 _298_ (
    .A_N(_102_),
    .B(_105_),
    .C(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__maj3_1 _299_ (
    .A(fetch_pc_i[19]),
    .B(_104_),
    .C(_109_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(fetch_rdata_i[31]),
    .B(_009_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(_064_),
    .B(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(_064_),
    .B(_114_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(fetch_pc_i[20]),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(fetch_pc_i[20]),
    .B(_115_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(_111_),
    .A2(_112_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _307_ (
    .A(_113_),
    .B(_118_),
    .Y(predict_branch_pc_o[20])
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(_117_),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _309_ (
    .A(fetch_pc_i[21]),
    .B(_115_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(_120_),
    .B(_122_),
    .Y(predict_branch_pc_o[21])
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(fetch_pc_i[21]),
    .A2(fetch_pc_i[20]),
    .B1(_116_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(_119_),
    .A2(_122_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _314_ (
    .A(fetch_pc_i[22]),
    .B(_115_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xor2_1 _315_ (
    .A(_124_),
    .B(_125_),
    .X(predict_branch_pc_o[22])
  );
  sky130_fd_sc_hd__maj3_1 _316_ (
    .A(fetch_pc_i[22]),
    .B(_116_),
    .C(_124_),
    .X(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(fetch_pc_i[23]),
    .B(_115_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(_126_),
    .B(_127_),
    .X(predict_branch_pc_o[23])
  );
  sky130_fd_sc_hd__and2_0 _319_ (
    .A(_125_),
    .B(_127_),
    .X(_128_)
  );
  sky130_fd_sc_hd__o2111ai_1 _320_ (
    .A1(_111_),
    .A2(_112_),
    .B1(_118_),
    .C1(_121_),
    .D1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o41ai_1 _321_ (
    .A1(fetch_pc_i[23]),
    .A2(fetch_pc_i[21]),
    .A3(fetch_pc_i[22]),
    .A4(fetch_pc_i[20]),
    .B1(_116_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(fetch_pc_i[24]),
    .B(_115_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _325_ (
    .A(_131_),
    .B(_133_),
    .Y(predict_branch_pc_o[24])
  );
  sky130_fd_sc_hd__maj3_1 _326_ (
    .A(fetch_pc_i[24]),
    .B(_116_),
    .C(_131_),
    .X(_134_)
  );
  sky130_fd_sc_hd__xnor2_1 _327_ (
    .A(fetch_pc_i[25]),
    .B(_115_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _329_ (
    .A(_134_),
    .B(_136_),
    .Y(predict_branch_pc_o[25])
  );
  sky130_fd_sc_hd__o21a_1 _330_ (
    .A1(fetch_pc_i[25]),
    .A2(fetch_pc_i[24]),
    .B1(_116_),
    .X(_137_)
  );
  sky130_fd_sc_hd__and3_1 _331_ (
    .A(_131_),
    .B(_132_),
    .C(_135_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(fetch_pc_i[26]),
    .B(_116_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xnor2_1 _333_ (
    .A(fetch_pc_i[26]),
    .B(_115_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _334_ (
    .A1(_137_),
    .A2(_138_),
    .B1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3_1 _335_ (
    .A(_137_),
    .B(_138_),
    .C(_140_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _336_ (
    .A(_141_),
    .SLEEP(_142_),
    .X(predict_branch_pc_o[26])
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_139_),
    .B(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xnor2_1 _338_ (
    .A(fetch_pc_i[27]),
    .B(_115_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xor2_1 _339_ (
    .A(_143_),
    .B(_144_),
    .X(predict_branch_pc_o[27])
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(_140_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a2111oi_0 _341_ (
    .A1(_129_),
    .A2(_130_),
    .B1(_133_),
    .C1(_136_),
    .D1(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o41a_1 _342_ (
    .A1(fetch_pc_i[25]),
    .A2(fetch_pc_i[27]),
    .A3(fetch_pc_i[24]),
    .A4(fetch_pc_i[26]),
    .B1(_116_),
    .X(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(fetch_pc_i[28]),
    .B(_116_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(fetch_pc_i[28]),
    .B(_115_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _345_ (
    .A1(_146_),
    .A2(_147_),
    .B1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _346_ (
    .A(_146_),
    .B(_147_),
    .C(_149_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _347_ (
    .A(_150_),
    .SLEEP(_151_),
    .X(predict_branch_pc_o[28])
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_148_),
    .B(_150_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(fetch_pc_i[29]),
    .B(_116_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _350_ (
    .A(fetch_pc_i[29]),
    .SLEEP(_116_),
    .X(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(_153_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xnor2_1 _352_ (
    .A(_152_),
    .B(_155_),
    .Y(predict_branch_pc_o[29])
  );
  sky130_fd_sc_hd__xnor2_1 _353_ (
    .A(fetch_pc_i[30]),
    .B(_115_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand3_1 _354_ (
    .A(_148_),
    .B(_150_),
    .C(_153_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and2_0 _355_ (
    .A(_154_),
    .B(_157_),
    .X(_158_)
  );
  sky130_fd_sc_hd__xor2_1 _356_ (
    .A(_156_),
    .B(_158_),
    .X(predict_branch_pc_o[30])
  );
  sky130_fd_sc_hd__a32oi_1 _357_ (
    .A1(_154_),
    .A2(_156_),
    .A3(_157_),
    .B1(_116_),
    .B2(fetch_pc_i[30]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _358_ (
    .A(fetch_pc_i[31]),
    .B(_115_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_159_),
    .B(_160_),
    .Y(predict_branch_pc_o[31])
  );
  assign \_29_$func$gold_elab.v:74$2.a  = 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \_29_$func$gold_elab.v:74$2.s  = 3'bxxx;
  assign \_29_$func$gold_elab.v:74$2.b  = 96'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign instr = fetch_rdata_i;
  assign imm_j_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[19:12], fetch_rdata_i[20], fetch_rdata_i[30:21], 1'b0 };
  assign imm_cj_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[8], fetch_rdata_i[10:9], fetch_rdata_i[6], fetch_rdata_i[7], fetch_rdata_i[2], fetch_rdata_i[11], fetch_rdata_i[5:3], 1'b0 };
  assign imm_cb_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[6:5], fetch_rdata_i[2], fetch_rdata_i[11:10], fetch_rdata_i[4:3], 1'b0 };
  assign imm_b_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[7], fetch_rdata_i[30:25], fetch_rdata_i[11:8], 1'b0 };
  assign { branch_imm[31:21], branch_imm[0] } = { branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], 1'b0 };
  assign _sv2v_0 = 1'b0;
  assign predict_branch_pc_o[0] = fetch_pc_i[0];
endmodule
