/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ibex_branch_predict(clk_i, rst_ni, fetch_rdata_i, fetch_pc_i, fetch_valid_i, predict_branch_taken_o, predict_branch_pc_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] fetch_rdata_i;
  wire [31:0] fetch_rdata_i;
  input [31:0] fetch_pc_i;
  wire [31:0] fetch_pc_i;
  input fetch_valid_i;
  wire fetch_valid_i;
  output predict_branch_taken_o;
  wire predict_branch_taken_o;
  output [31:0] predict_branch_pc_o;
  wire [31:0] predict_branch_pc_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _sv2v_0;
  wire [31:0] branch_imm;
  wire [31:0] imm_b_type;
  wire [31:0] imm_cb_type;
  wire [31:0] imm_cj_type;
  wire [31:0] imm_j_type;
  wire [31:0] instr;
  wire instr_b;
  wire instr_b_taken;
  wire instr_cb;
  wire instr_cj;
  wire instr_j;
  assign predict_branch_pc_o = fetch_pc_i + branch_imm;
  assign instr_cb = _02_ & _07_;
  assign instr_cj = _02_ & _08_;
  assign _00_ = instr_b & fetch_rdata_i[31];
  assign _01_ = instr_cb & fetch_rdata_i[12];
  assign predict_branch_taken_o = fetch_valid_i & _10_;
  assign instr_b = fetch_rdata_i[6:0] == 7'h63;
  assign instr_j = fetch_rdata_i[6:0] == 7'h6f;
  assign _03_ = fetch_rdata_i[15:13] == 3'h6;
  assign _04_ = fetch_rdata_i[15:13] == 3'h7;
  assign _05_ = fetch_rdata_i[15:13] == 3'h1;
  assign _02_ = fetch_rdata_i[1:0] == 2'h1;
  assign _06_ = fetch_rdata_i[15:13] == 3'h5;
  assign _07_ = _03_ | _04_;
  assign _08_ = _06_ | _05_;
  assign instr_b_taken = _00_ | _01_;
  assign _09_ = instr_j | instr_cj;
  assign _10_ = _09_ | instr_b_taken;
  function [31:0] _29_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _29_ = b[31:0];
      3'b?1?:
        _29_ = b[63:32];
      3'b1??:
        _29_ = b[95:64];
      default:
        _29_ = a;
    endcase
  endfunction
  assign branch_imm = _29_({ fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[7], fetch_rdata_i[30:25], fetch_rdata_i[11:8], 1'h0 }, { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[19:12], fetch_rdata_i[20], fetch_rdata_i[30:21], 1'h0, fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[8], fetch_rdata_i[10:9], fetch_rdata_i[6], fetch_rdata_i[7], fetch_rdata_i[2], fetch_rdata_i[11], fetch_rdata_i[5:3], 1'h0, fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[6:5], fetch_rdata_i[2], fetch_rdata_i[11:10], fetch_rdata_i[4:3], 1'h0 }, { instr_j, instr_cj, instr_cb });
  assign instr = fetch_rdata_i;
  assign imm_cb_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[6:5], fetch_rdata_i[2], fetch_rdata_i[11:10], fetch_rdata_i[4:3], 1'h0 };
  assign imm_cj_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[8], fetch_rdata_i[10:9], fetch_rdata_i[6], fetch_rdata_i[7], fetch_rdata_i[2], fetch_rdata_i[11], fetch_rdata_i[5:3], 1'h0 };
  assign imm_b_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[7], fetch_rdata_i[30:25], fetch_rdata_i[11:8], 1'h0 };
  assign imm_j_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[19:12], fetch_rdata_i[20], fetch_rdata_i[30:21], 1'h0 };
  assign _sv2v_0 = 1'h0;
endmodule
